services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src
      - ./src/entrypoint.sh:/usr/bin/entrypoint.sh
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tutorial
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data:
