services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/tutorial
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DB: tutorial
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -p 8080 -b 0.0.0.0"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tutorial
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data:
